# Generated by Django 5.2.17 on 2026-09-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Frontline Officer'), ('ADMIN', 'System Administrator')], db_index=True, default='CITIZEN', max_length=20, verbose_name='User Role'),
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(db_index=True, max_length=150, verbose_name='Department Name')),
                ('lgd_jurisdiction_code', models.CharField(db_index=True, max_length=64, verbose_name='LGD Jurisdiction Code')),
                ('officer_designation', models.CharField(choices=[('Sanitary Inspector', 'Sanitary Inspector'), ('Ward Officer', 'Ward Officer'), ('Panchayat Secretary', 'Panchayat Secretary'), ('Village Development Officer (VDO)', 'Village Development Officer (VDO)'), ('Assistant Town Planner', 'Assistant Town Planner'), ('Revenue Inspector', 'Revenue Inspector'), ('Village Administrative Officer (VAO)', 'Village Administrative Officer (VAO)'), ('Patwari', 'Patwari'), ('Assistant Engineer (AE)', 'Assistant Engineer (AE)'), ('Junior Engineer (JE)', 'Junior Engineer (JE)'), ('Station House Officer (SHO)', 'Station House Officer (SHO)'), ('Medical Officer In-Charge (MO)', 'Medical Officer In-Charge (MO)'), ('Block Education Officer (BEO)', 'Block Education Officer (BEO)'), ('Headmaster', 'Headmaster')], max_length=100, verbose_name='Officer Designation')),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Govt Employee / Badge ID')),
                ('jurisdiction_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ward / Circle / Village Name')),
                ('is_on_duty', models.BooleanField(default=True, verbose_name='Available On-Duty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Officer User Account')),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
                'ordering': ['department_name', 'lgd_jurisdiction_code'],
            },
        ),
    ]
