# Generated by Django 5.2.17 on 2026-09-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_role_officerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Frontline Officer'), ('CENTRAL_DESK', 'Central Desk Triage Operator'), ('ADMIN', 'System Administrator')], db_index=True, default='CITIZEN', max_length=20, verbose_name='User Role'),
        ),
    ]
