# Generated by Django 5.2.17 on 2026-09-25 00:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0004_complaint_is_reopened_complaint_previous_resolved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('boundary_type', models.CharField(choices=[('STATE', 'State Boundary'), ('DISTRICT', 'District Boundary'), ('MUNICIPALITY', 'Municipal Boundary'), ('ZONE', 'Zone Boundary'), ('WARD', 'Ward Boundary')], default='WARD', max_length=32)),
                ('geojson_data', models.JSONField(default=dict)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('zoom_level', models.IntegerField(default=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spatial Boundary',
                'verbose_name_plural': 'Spatial Boundaries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotspotCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('department_category', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('cluster_center_lat', models.FloatField(db_index=True)),
                ('cluster_center_lng', models.FloatField(db_index=True)),
                ('radius_meters', models.FloatField(default=300.0)),
                ('reports_count', models.PositiveIntegerField(default=1)),
                ('severity_score', models.FloatField(default=0.0)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('capex_recommendation_title', models.CharField(blank=True, max_length=255, null=True)),
                ('capex_estimated_budget_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('capex_recommendation_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaints', models.ManyToManyField(blank=True, related_name='hotspot_clusters', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Civic Hotspot Cluster',
                'verbose_name_plural': 'Civic Hotspot Clusters',
                'ordering': ['-severity_score'],
            },
        ),
    ]
