apiVersion: v1
kind: ConfigMap
metadata:
  name: dpip-config
  namespace: dpip
  labels:
    app.kubernetes.io/name: dpip-platform
data:
  DJANGO_SETTINGS_MODULE: "dpi_core.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOW_ALL_ORIGINS: "True"
  USE_SQLITE: "True"
  STATE_CODE: "TN"
  STATE_NAME: "Tamil Nadu"
  DEFAULT_MAP_LAT: "13.0827"
  DEFAULT_MAP_LNG: "80.2707"
  NEXT_PUBLIC_API_URL: "/api"
