# Generated by Django 5.2.17 on 2026-09-22 14:13

import complaints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, default=complaints.models.generate_unique_tracking_code, editable=False, max_length=32, unique=True, verbose_name='Unique Tracking Code')),
                ('description', models.TextField(verbose_name='Complaint Description')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/%Y/%m/', verbose_name='Voice Note Audio')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='complaint_media/%Y/%m/', verbose_name='Photos / Documents')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('address', models.CharField(max_length=500, verbose_name='Exact Address')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Resolution Notes')),
                ('resolution_proof', models.FileField(blank=True, null=True, upload_to='resolution_proofs/%Y/%m/', verbose_name='Resolution Proof Files')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Citizen User')),
            ],
            options={
                'verbose_name': 'Citizen Complaint',
                'verbose_name_plural': 'Citizen Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
