# Generated by Django 5.2.17 on 2026-09-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_role_officerprofile'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-ai_severity_score', '-created_at'], 'verbose_name': 'Citizen Complaint', 'verbose_name_plural': 'Citizen Complaints'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='action_taken_report',
            field=models.TextField(blank=True, null=True, verbose_name='Action Taken Report (ATR)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_analysis_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI Triage Summary & Urgency Analysis'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_severity_score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='AI Severity Score (Urgency)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='accounts.officerprofile', verbose_name='Assigned Frontline Officer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_category',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Classified Department Category'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lgd_jurisdiction_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='LGD Jurisdiction Code'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registered At'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_proof',
            field=models.FileField(blank=True, null=True, upload_to='resolution_proofs/%Y/%m/', verbose_name='Photographic Resolution Proof'),
        ),
    ]
