# Generated by Django 5.2.17 on 2026-09-24 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('complaints', '0002_alter_complaint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='central_desk_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Central Desk Dispatch Operator'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='central_desk_reviewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Central Desk Reviewed / Dispatched'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gemini_suggested_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_suggested_complaints', to='accounts.officerprofile', verbose_name='Gemini Recommended Officer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reassigned_to_central_desk',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Reassigned Back to Central Desk'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reassignment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Officer Reassignment Reason'),
        ),
    ]
