# Generated by Django 5.2.17 on 2026-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_central_desk_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_reopened',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Grievance Reopened'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='previous_resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previous Resolution Timestamp'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Times Reopened'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Citizen Reopen Reason'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reopened At'),
        ),
    ]
