# Generated by Django 5.2.17 on 2026-09-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_is_reopened_complaint_previous_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='detected_language',
            field=models.CharField(default='en', max_length=32, verbose_name='Detected Audio Spoken Language'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Escalated Timestamp'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_level',
            field=models.CharField(choices=[('LEVEL_1_FIELD', 'Level 1: Frontline Field Officer'), ('LEVEL_2_DIVISION', 'Level 2: Assistant Executive Engineer / Division Head'), ('LEVEL_3_COMMISSIONER', 'Level 3: Municipal Commissioner / District Collector')], db_index=True, default='LEVEL_1_FIELD', max_length=30, verbose_name='Current Escalation Hierarchy Level'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Statutorily Escalated'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='SLA Resolution Deadline'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_duration_hours',
            field=models.PositiveIntegerField(default=48, verbose_name='Statutory SLA Target Hours'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vision_audit_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Computer Vision Quality Notes'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vision_confidence_score',
            field=models.FloatField(default=0.0, verbose_name='Vision Confidence Score'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vision_verification_status',
            field=models.CharField(choices=[('NOT_INSPECTED', 'Not Inspected'), ('VERIFIED', 'Verified Resolved'), ('FLAGGED', 'Suspected Unresolved / Fraudulent'), ('INCONCLUSIVE', 'Inconclusive / Manual Review')], db_index=True, default='NOT_INSPECTED', max_length=30, verbose_name='AI Vision Verification Status'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='voice_transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Automated Speech Transcript'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='voice_translated_english',
            field=models.TextField(blank=True, null=True, verbose_name='Voice Translation (English)'),
        ),
    ]
