# Generated by Django 5.2.17 on 2026-09-26 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_detected_language_complaint_escalated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Tracking Code (if applicable)')),
                ('citizen_name', models.CharField(default='Citizen', max_length=255, verbose_name='Citizen Name')),
                ('citizen_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact / Phone / Email')),
                ('department_category', models.CharField(db_index=True, default='General Municipal Services', max_length=150, verbose_name='Department / Civic Service Category')),
                ('ward_or_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ward / Zone / Locality')),
                ('overall_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Overall Experience (1-5)')),
                ('resolution_satisfaction', models.PositiveSmallIntegerField(default=5, verbose_name='Grievance Resolution Satisfaction (1-5)')),
                ('officer_timeliness', models.PositiveSmallIntegerField(default=5, verbose_name='Officer Promptness & Timeliness (1-5)')),
                ('work_quality', models.PositiveSmallIntegerField(default=5, verbose_name='Quality of Work & Durability (1-5)')),
                ('cleanliness_score', models.PositiveSmallIntegerField(default=5, verbose_name='Cleanliness & Site Restoration (1-5)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Qualitative Feedback / Suggestions')),
                ('photo_proof', models.FileField(blank=True, null=True, upload_to='feedback_proofs/%Y/%m/', verbose_name='Citizen Verification Photo')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend DPIP Resolution Services')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_records', to='complaints.complaint', verbose_name='Associated Grievance Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civic_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Citizen User Account')),
            ],
            options={
                'verbose_name': 'Civic Feedback & Survey',
                'verbose_name_plural': 'Civic Feedback & Surveys',
                'ordering': ['-created_at'],
            },
        ),
    ]
