# Generated by Django 5.2.17 on 2026-09-25 00:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(db_index=True, unique=True)),
                ('previous_hash', models.CharField(db_index=True, max_length=64)),
                ('current_hash', models.CharField(db_index=True, max_length=64)),
                ('actor', models.CharField(db_index=True, max_length=255)),
                ('actor_id', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('resource', models.CharField(db_index=True, max_length=128)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Ledger Event',
                'verbose_name_plural': 'Audit Ledger Events',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['resource', 'resource_id'], name='audit_audit_resourc_acbb38_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_e5b6a1_idx')],
            },
        ),
    ]
